// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQTqSQQAix9AHGReKX0-b9QsVn_G_oxA',
    appId: '1:1795772074:web:1af788be2b629735078ad3',
    messagingSenderId: '1795772074',
    projectId: 'my-chat-1e42f',
    authDomain: 'my-chat-1e42f.firebaseapp.com',
    storageBucket: 'my-chat-1e42f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfB2_ClhnohRWMnTlUCqGQF6wkC_IAfYU',
    appId: '1:1795772074:android:df8944c503d04bfc078ad3',
    messagingSenderId: '1795772074',
    projectId: 'my-chat-1e42f',
    storageBucket: 'my-chat-1e42f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRyV8aPbz0L1aVPczJT-ICSIkjtKHviM',
    appId: '1:1795772074:ios:8cef534ffbe4e90e078ad3',
    messagingSenderId: '1795772074',
    projectId: 'my-chat-1e42f',
    storageBucket: 'my-chat-1e42f.appspot.com',
    iosBundleId: 'com.example.flutterGit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRyV8aPbz0L1aVPczJT-ICSIkjtKHviM',
    appId: '1:1795772074:ios:8cef534ffbe4e90e078ad3',
    messagingSenderId: '1795772074',
    projectId: 'my-chat-1e42f',
    storageBucket: 'my-chat-1e42f.appspot.com',
    iosBundleId: 'com.example.flutterGit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAQTqSQQAix9AHGReKX0-b9QsVn_G_oxA',
    appId: '1:1795772074:web:402ff69caf9ec262078ad3',
    messagingSenderId: '1795772074',
    projectId: 'my-chat-1e42f',
    authDomain: 'my-chat-1e42f.firebaseapp.com',
    storageBucket: 'my-chat-1e42f.appspot.com',
  );
}
